stages:
  - build
  - deploy

build-linux:
  stage: build
  script:
    - conda build --output-folder=dist conda/release
  artifacts:
    paths:
      - dist/
  tags:
    - conda
    - linux

build-win:
  stage: build
  script:
    - call conda build --output-folder=dist conda/release
  artifacts:
    paths:
      - dist/
  tags:
    - conda
    - win

deploy_devel:
  stage: deploy
  environment:
    name: devel/$CI_COMMIT_REF_NAME
    url: http://bcu-ci.esrf.fr/devel
  dependencies:
    - build-linux
    - build-win
  script:
    - cp -Rf dist/* /conda-devel/
    - conda index /conda-devel/
  tags:
    - conda
    - linux
  only:
    - branches
  except:
    - stable
  when: manual

deploy_stable:
  stage: deploy
  environment:
    name: production
    url: http://bcu-ci.esrf.fr/stable
  dependencies:
    - build-linux
    - build-win
  script:
    - cp -Rf dist/* /conda/
    - conda index /conda/
  tags:
    - conda
    - linux
  only:
    - tags
    - stable
