# image : docker-registry.esrf.fr/bcu/lima-ci-debian8:latest
#before_script :

stages:
  - build
  - test

build-python2 :
  stage: build
  script:
    - update-alternatives --set python /usr/bin/python2.7
    - cmake -Bbuild -H. -DPROCESSLIB_ENABLE_PYTHON=1 -DPROCESSLIB_ENABLE_TESTS=1
    - cmake --build build
    - ls -l
  artifacts:
    paths:
    - build/

build-python3 :
  stage: build
  script:
    - update-alternatives --set python /usr/bin/python3.4
    - cmake -Bbuild -H. -DPROCESSLIB_ENABLE_PYTHON=1 -DPROCESSLIB_ENABLE_TESTS=1
    - cmake --build build
    - ls -l
  artifacts:
    paths:
    - build/

test-python2 :
  stage: test
  dependencies:
    - build-python2
  script:
    - update-alternatives --set python /usr/bin/python2.7
    - cd build/
    - ctest --timeout 10 --output-on-failure

test-python3 :
  stage: test
  dependencies:
    - build-python3
  script:
    - update-alternatives --set python /usr/bin/python3.4
    - cd build/
    - ctest --timeout 10 --output-on-failure
