#!/bin/bash
cmake -Bbuild -H. -GNinja -DPROCESSLIB_ENABLE_PYTHON=1 -DPROCESSLIB_ENABLE_TESTS=1 -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_FIND_ROOT_PATH=$PREFIX -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPython3_FIND_STRATEGY=LOCATION
cmake --build build --target install
