# Strip the 'v' from the version tag
{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG[1:] %}
{% else %}
{%   set version = "0.0.0" %}
{% endif %}

package:
  name: processlib
  version: {{ version }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - sip 4.19.* # API v12.7
    - gsl 2.2.*
    - pthreads-win32 # [win]
  build:
    - ninja
    - cmake
    - {{ compiler('cxx') }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('sip', min_pin='x.x.x', max_pin='x') }}
    - {{ pin_compatible('gsl', max_pin='x.x') }}
    - {{ pin_compatible('pthreads-win32') }} # [win]

test:
  imports:
    - processlib

about:
  home: https://github.com/esrf-bliss/Processlib
  license: GPL
  license_file: COPYING
  summary: a compagnion library of LImA for basic image processing
